openapi: 3.0.0
info:
  title: Заказ ресурсов на облаке
  version: 0.0.1
servers: 
  - url: http://localhost:8080/api/v1/
    description: Dev server
paths:
  /clouds:
    get:
      summary: Метод получения списка ресурсов на облаке
      tags:
        - Clouds
      operationId: getAllClouds
      responses:
        "200":
          description: Успешный ответ со списком ресурсов на облаке
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Clouds"
        "default":
          description: Все остальное
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"
    post:
      summary: Создание заказа в облаке 
      tags:
        - Clouds
      operationId: createCloud
      requestBody:
        content:
          application/json:
            schema:
                $ref: "#/components/schemas/Error"
      responses:
        "200":
          description: Успешный ответ со списком ресурсов на облаке
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Clouds"
        "default":
          description: Все остальное
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"
  /clouds/{cloud_id}:
    get:
      summary: Метод получения заказа на облако по ID
      tags:
        - Clouds
      operationId: getCloudByID
      parameters:
        - name: cloud_id
          in: path
          required: true
          description: Идентификатор заказа облака
          schema:
            type: string
          example: f927h7
      responses:
        "200":
          description: Успешный ответ c ID заказа
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Clouds"
        "404":
          description: Заказ с ID не найден
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"
        "default":
          description: Все остальное
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"
    delete:
      summary: Метод отмены заказа на облако по ID
      tags:
        - Clouds
      operationId: cancelCloudByID
      parameters:
        - name: cloud_id
          in: path
          required: true
          description: Идентификатор заказа облака
          schema:
            type: string
          example: f927h7
      responses:
        "200":
          description: Успешный ответ c ID заказа
          content:
            application/json: {}
        "404":
          description: Заказ с ID не найден
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"
        "default":
          description: Все остальное
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"
    put:
      summary: Метод обновления заказа на облако по ID
      tags:
        - Clouds
      operationId: updateCloudByID
      parameters:
        - name: cloud_id
          in: path
          required: true
          description: Идентификатор заказа облака
          schema:
            type: string
          example: d94g66f
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/Cloud"
      responses:
        "200":
          description: Успешный ответ c обновленной информацией о заказе
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Cloud"
        "404":
          description: Заказ с ID не найден
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"
        "default":
          description: Все остальное
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"
  /clients:
    get:
      summary: Метод для получения списка всех клиентов
      tags:
        - Clients
      operationId: getAllClients
      responses:
        "200":
          description: Успешный ответ со списком всех клиентов
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/Client"
        "default":
          description: Все остальное
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"
components:
  schemas:
    Cloud:
      type: object
      required:
        - id_client
        - OS
        - RAM
        - CPU
        - SSD
      properties:
        cloud_id: 
          type: string
          example: f102b615
        id_client:
          type: string
          example: f102b615
        OS:
          type: string
          enum:
            - Windows
            - Linux
          description: Операционная система сервера
        RAM:
          type: string
          example: 128
          description: Объем оперативной памяти
        CPU:
          type: string
          example: 8
          description: Количество ядер процессора
        SSD:
          type: string
          example: 512
          description: Объем жесткого диска
    Clouds:
      type: array
      items:
        $ref: "#/components/schemas/Cloud"
    Error:
      type: object
      required:
        - code
        - message
      properties:
        code:
          type: integer
        message:
          type: string
    Client:
      type: object
      required:
        - id
        - name
        - email
        - hash
      properties:
        id: 
          type: string
          example: c102b615
        name:
          type: string
          example: John Smith
        email:
          type: string
          example: johnsmith@example.com
        hash:
          type: integer
          example: 563928125
        
        
      