/*
 * Заказ ресурсов на облаке
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package io.swagger.client.api;

import io.swagger.client.model.Cloud;
import io.swagger.client.model.Clouds;
import io.swagger.client.model.Error;
import org.junit.Test;
import org.junit.Ignore;


import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;


/**
 * API tests for CloudsApi
 */
@Ignore
public class CloudsApiTest {

    private final CloudsApi api = new CloudsApi();

    /**
     * Метод отмены заказа на облако по ID
     *
     * 
     *
     * @throws Exception
     *          if the Api call fails
     */
    @Test
    public void cancelCloudByIDTest() throws Exception {
        String cloudId = null;
        api.cancelCloudByID(cloudId);

        // TODO: test validations
    }
    /**
     * Создание заказа в облаке
     *
     * 
     *
     * @throws Exception
     *          if the Api call fails
     */
    @Test
    public void createCloudTest() throws Exception {
        Error body = null;
        Clouds response = api.createCloud(body);

        // TODO: test validations
    }
    /**
     * Метод получения списка ресурсов на облаке
     *
     * 
     *
     * @throws Exception
     *          if the Api call fails
     */
    @Test
    public void getAllCloudsTest() throws Exception {
        Clouds response = api.getAllClouds();

        // TODO: test validations
    }
    /**
     * Метод получения заказа на облако по ID
     *
     * 
     *
     * @throws Exception
     *          if the Api call fails
     */
    @Test
    public void getCloudByIDTest() throws Exception {
        String cloudId = null;
        Clouds response = api.getCloudByID(cloudId);

        // TODO: test validations
    }
    /**
     * Метод обновления заказа на облако по ID
     *
     * 
     *
     * @throws Exception
     *          if the Api call fails
     */
    @Test
    public void updateCloudByIDTest() throws Exception {
        String cloudId = null;
        Cloud body = null;
        Cloud response = api.updateCloudByID(cloudId, body);

        // TODO: test validations
    }
}
